name: Publish Package to npm
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: npm run build

      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}